server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/productdb
    username: postgres
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
      format_sql: true
    show-sql: false

  sql:
    init:
      mode: never

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
