server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb?gssEncMode=disable
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
#        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  application:
 #   name: ORDER-SERVICE
  config:
    import: configserver:http://localhost:8191

  sql:
      init:
        mode: never

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
