server:
  port: 8081
spring:
  datasource:
    # url: jdbc:postgresql://172.24.0.2:5432/productdb
    url: jdbc:h2:mem:orderdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  #    hikari:
  #     allow-pool-suspension: true
  #    connection-timeout: 60000
  jpa:
    #    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
      format_sql: true
    show-sql: false

  sql:
    init:
      mode: never

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
